experiment/LIFT/LIFT_optitrack_client:
  ros__parameters:
    dt: 0.01

    multicast_group: '239.255.42.99'
    multicast_port: 1511
    body_id: 516

    odom_topic: 'optitrack/odom'

    pub_accel: false
    lin_accel_topic: 'optitrack/lin_accel'
    ang_accel_topic: 'optitrack/ang_accel'