experiment/LIFT/LIFT_control:
  ros__parameters:
    dt: 0.1
    n_laps: 100
    n_init_laps: 1

    simulation: false

    v_long_max: 3.5
    v_long_min: 0.0
    v_tran_max: 10
    v_tran_min: -10
    w_psi_max : 10
    w_psi_min : -10
    u_a_max: 1.9
    u_a_min: -1.9
    u_steer_max: 0.436
    u_steer_min: -0.436
    u_a_rate_max: 5
    u_a_rate_min: -5
    u_steer_rate_max: 1.5
    u_steer_rate_min: -1.5

    pid_steer_params:
      Kp: 0.3  # 1.0
      Ki: 0.001  # 0.15
      Kd: 0.0  # 0.0
    pid_speed_params:
      Kp: 0.5
      Ki: 0.1  # 0.5
      Kd: 0.0  # 0.02
      x_ref: 1.2

    mpc_params:
      N: 15
      
      delay: [2, 2]

      qp_iters: 1
      damping: 0.0
      keep_init_safe_set: false

      state_scaling: [4.0, 3.0, 7.0, 6.283185307179586, 20.0, 1.0]
      input_scaling: [2.0, 0.436]

      terminal_cost_scaling: 1.0

      n_ss_pts: 48
      n_ss_its: 4

      convex_hull_slack_quad: [500, 500, 500, 500, 500, 500]
      convex_hull_slack_lin: [0, 0, 0, 0, 0, 0]

      soft_state_bound_idxs: [5]
      soft_state_bound_quad: [50]
      soft_state_bound_lin: [250]
      regression_regularization: 0.001
      regression_state_out_idxs:
        i0: [0]
        i1: [1]
        i2: [2]
      regression_state_in_idxs:
        i0: [0, 1, 2]
        i1: [0, 1, 2]
        i2: [0, 1, 2]
      regression_input_in_idxs:
        i0: [0]
        i1: [1]
        i2: [1]

      nearest_neighbor_weights:
        i0: [1.0, 1.0, 1.0, 1.0, 1.0]
        i1: [1.0, 1.0, 1.0, 1.0, 1.0]
        i2: [1.0, 1.0, 1.0, 1.0, 1.0]
      nearest_neighbor_bw: 10.0
      nearest_neighbor_max_points: 15

      safe_set_init_data_file: '~/barc_data/barc_run_ltv_mpc_02-28-2024_13-09-27/barc_run_ltv_mpc_02-28-2024_13-09-27_0.db3'
      # safe_set_init_data_file: ''
      safe_set_topic: '/experiment/barc_2/state_input_log'
      
      qp_interface: 'casadi'
      qp_solver: 'osqp'

      verbose: false

    dynamics_config:
      model_name: 'dynamic_bicycle_cl'

      discretization_method: 'rk4'

      wheel_dist_front: 0.13
      wheel_dist_rear: 0.13
      wheel_dist_center_front: 0.1
      wheel_dist_center_rear: 0.1
      bump_dist_front: 0.15
      bump_dist_rear: 0.15
      bump_dist_center: 0.1

      mass: 2.2187
      gravity: 9.81
      yaw_inertia: 0.02723

      # Tire model parameters:
      tire_model: 'pacejka'
      wheel_friction: 0.9
      pacejka_b_front: 5.0
      pacejka_c_front: 2.28
      pacejka_b_rear: 5.0
      pacejka_c_rear: 2.28

      simple_slip: false

      M: 10

      code_gen: true
      jit: true
      opt_flag: 'O3'

# experiment/barc_2/barc_2_control:
#   ros__parameters:
#     dt: 0.1
#     n_laps: 22
#     n_init_laps: 1

#     simulation: false

#     v_long_max: 3.5
#     v_long_min: 0.0
#     v_tran_max: 10
#     v_tran_min: -10
#     w_psi_max : 10
#     w_psi_min : -10
#     u_a_max: 1.9
#     u_a_min: -1.9
#     u_steer_max: 0.436
#     u_steer_min: -0.436
#     u_a_rate_max: 5
#     u_a_rate_min: -5
#     u_steer_rate_max: 1.5
#     u_steer_rate_min: -1.5

#     pid_steer_params:
#       Kp: 0.3  # 1.0
#       Ki: 0.001  # 0.15
#       Kd: 0.0  # 0.0
#     pid_speed_params:
#       Kp: 0.5
#       Ki: 0.1  # 0.5
#       Kd: 0.0  # 0.02
#       x_ref: 1.2

#     mpc_params:
#       N: 15
      
#       delay: [2, 2]

#       qp_iters: 1
#       damping: 0.0
#       keep_init_safe_set: false

#       state_scaling: [4.0, 3.0, 7.0, 6.283185307179586, 20.0, 1.0]
#       input_scaling: [2.0, 0.436]

#       terminal_cost_scaling: 1.0
#       adaptive_scaling: true

#       n_ss_pts: 48
#       n_ss_its: 4

#       convex_hull_slack_quad: [500, 500, 500, 500, 500, 500]
#       convex_hull_slack_lin: [0, 0, 0, 0, 0, 0]

#       soft_state_bound_idxs: [5]
#       soft_state_bound_quad: [50]
#       soft_state_bound_lin: [250]

#       regression_regularization: 0.001
#       regression_state_out_idxs:
#         i0: [0]
#         i1: [1]
#         i2: [2]
#       regression_state_in_idxs:
#         i0: [0, 1, 2]
#         i1: [0, 1, 2]
#         i2: [0, 1, 2]
#       regression_input_in_idxs:
#         i0: [0]
#         i1: [1]
#         i2: [1]

#       nearest_neighbor_weights:
#         i0: [1.0, 1.0, 1.0, 1.0, 1.0]
#         i1: [1.0, 1.0, 1.0, 1.0, 1.0]
#         i2: [1.0, 1.0, 1.0, 1.0, 1.0]
#       nearest_neighbor_bw: 3.0
#       nearest_neighbor_max_points: 15

#       safe_set_init_data_file: '~/barc_data/barc_run_ltv_mpc_02-28-2024_13-09-27/barc_run_ltv_mpc_02-28-2024_13-09-27_0.db3'
#       # safe_set_init_data_file: ''
#       safe_set_topic: '/experiment/barc_2/state_input_log'
      
#       qp_interface: 'casadi'
#       qp_solver: 'osqp'

#       verbose: false

#     dynamics_config:
#       model_name: 'dynamic_bicycle_cl'

#       discretization_method: 'rk4'

#       wheel_dist_front: 0.13
#       wheel_dist_rear: 0.13
#       wheel_dist_center_front: 0.1
#       wheel_dist_center_rear: 0.1
#       bump_dist_front: 0.15
#       bump_dist_rear: 0.15
#       bump_dist_center: 0.1

#       mass: 2.2187
#       gravity: 9.81
#       yaw_inertia: 0.02723

#       # Tire model parameters:
#       tire_model: 'pacejka'
#       wheel_friction: 0.9
#       pacejka_b_front: 5.0
#       pacejka_c_front: 2.28
#       pacejka_b_rear: 5.0
#       pacejka_c_rear: 2.28

#       simple_slip: false

#       M: 10

#       code_gen: true
#       jit: true
#       opt_flag: 'O3'