experiment/LIFT/LIFT_estimator:
  ros__parameters:
    dt: 0.02

    estimate_accel: false

    ot_params:
      odom_topic: 'optitrack/odom'
      lin_accel_topic: 'optitrack/lin_accel'
      ang_accel_topic: 'optitrack/ang_accel'

      origin_x: -3.4669
      origin_y: 1.9382
      origin_z: 0.0

      origin_roll: 0.0
      origin_pitch: 0.0
      origin_yaw: -1.5707963267948966

      offset_long: -0.21
      offset_tran: 0.0
      offset_vert: 0.0

      offset_roll: 0.0
      offset_pitch: 0.0
      offset_yaw: 0.0
